import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@/styles/reset.css";
import Layout from "@/components/Layout/Layout";
import QueryProvider from "./_components/QueryProvider";
import MockInterceptorProvider from "./_components/MockInterceptorProvider";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=League+Gothic&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="body">
        <QueryProvider>
          <Layout>
            <MockInterceptorProvider />
            {children}
          </Layout>
        </QueryProvider>
      </body>
    </html>
  );
}
