import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@/styles/reset.css";
import Layout from "@/components/Layout/Layout";
import QueryProvider from "./_components/QueryProvider";
import MockInterceptorProvider from "./_components/MockInterceptorProvider";
import { leagueGothic } from "@/styles/googleFont";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`body ${leagueGothic.className}`}>
        <QueryProvider>
          <Layout>
            <MockInterceptorProvider />
            {children}
          </Layout>
        </QueryProvider>
      </body>
    </html>
  );
}
